import { useQuery } from "@tanstack/react-query";

import type { InferGetServerSidePropsType, NextPage } from "next";
import Head from "next/head";
import { CiMapPin } from "react-icons/ci";
import { GetServerSideProps } from "next";
import { GetProductsResponse, getProducts } from "../src/api";
import NavBar from "../components/NavBar";
import Link from "next/link";
import { BG_IMG, BG_IMG_2, GOOGLE_MAP_ADDRESS_LINK } from "../shared";
import BookingForm from "../components/BookingForm/BookingForm";
import Banner from "../components/Banner";
import Gallery from "../components/Gallery/Gallery";

type ServerSideProps = {
  getProductsResponse: GetProductsResponse;
};

export const getServerSideProps: GetServerSideProps<ServerSideProps> = async (
  context
) => {
  const response = await getProducts();
  return { props: { getProductsResponse: response } };
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ getProductsResponse }) => {
  const { data, isLoading } = useQuery({
    queryKey: ["products"],
    queryFn: getProducts,
    initialData: getProductsResponse,
  });

  return (
    <>
      <Head>
        <title>The Princess of Arena Cam Ranh Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-[Montserrat]">
        <div
          className="bg-no-repeat bg-cover min-h-screen flex flex-col"
          style={{ backgroundImage: `url(${BG_IMG})` }}
        >
          <NavBar />
          <Banner />
        </div>

        <div className="h-screen">
          <Gallery />
        </div>

        <div
          className="bg-no-repeat bg-cover min-h-screen flex flex-col justify-center items-center"
          style={{ backgroundImage: `url(${BG_IMG_2})` }}
        >
          <BookingForm />
        </div>
      </main>
    </>
  );
};

export default Home;
