import type { NextPage } from "next";
import Head from "next/head";

import NavBar from "../components/NavBar";
import { BG_IMG, BG_IMG_2 } from "../shared";
import BookingForm from "../components/BookingForm/BookingForm";
import Banner from "../components/Banner";
import Gallery from "../components/Gallery/Gallery";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>The Princess of Arena Cam Ranh Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-[Montserrat]">
        <div
          className="bg-no-repeat bg-cover min-h-screen flex flex-col"
          style={{ backgroundImage: `url(${BG_IMG})` }}
        >
          <NavBar />
          <Banner />
        </div>

        <div className="h-screen">
          <Gallery />
        </div>

        <div
          className="bg-no-repeat bg-cover min-h-screen flex flex-col justify-center items-center"
          style={{ backgroundImage: `url(${BG_IMG_2})` }}
        >
          <BookingForm />
        </div>
      </main>
    </>
  );
};

export default Home;
